export const portfolioData = [
  {
    project: "Hupu",
    slug: "hupu",
    websiteURL: 'https://hupu.co.za/',
    techStack: ['Vue.JS', 'C#', 'HomeBrew CMS'],
    favourited: true,
    shortDescription: "Hupu, developed by Nologo, delivers groceries directly from farms to consumers. When I joined Nologo, Hupu was finishing its testing phase and quickly became a key project.\n\nThe platform's growth accelerated during the COVID-19 pandemic, which heightened demand for direct-to-consumer grocery delivery due to lockdowns and limited shopping options.",
    longDescription: "From 2020 to 2021, onTap partnered with our agency to elevate its digital presence. We modernized their platform with Vue Storefront and integrated it with Nologo's 'Advance' backend system in C#.\n\nOur aim was to boost user engagement and streamline backend operations to align with onTap's business goals.",
    mainImage: '/hupu-squared.jpg',
    mainImageAlt: 'Hupu banner image',
    topBanner: '/hupu-squared.jpg',
    roleOnProject: 'Frontend Developer',
    problemOneImage: '',
    problemOneText: '',
    problemTwoImage: '',
    problemTwoText: ''
  },
  {
    project: "onTap",
    slug: "ontap",
    websiteURL: 'https://www.ontap.co.za/',
    techStack: ['Vue.JS', 'C# backend', 'Vue Storefront'],
    favourited: true,
    shortDescription: "From 2020 to 2021, onTap partnered with our agency to elevate its digital presence. We modernized their platform with Vue Storefront and integrated it with Nologo's 'Advance' backend system in C#.\n\nOur aim was to boost user engagement and streamline backend operations to align with onTap's business goals.",
    longDescription: "From 2020 to 2021, our agency partnered with onTap to revamp their digital platform. We modernized the frontend using Vue Storefront, which provided a sleek, responsive design that enhanced user engagement. This upgrade ensured a more intuitive and visually appealing interface for onTap's customers.\n\nSimultaneously, we integrated Nologo's 'Advance' backend system, built in C#, to optimize and streamline backend operations. This integration offered a scalable, efficient infrastructure, improving data management and system performance.\n\nThe combined frontend and backend enhancements aimed to align with onTap's business goals by boosting user interaction and operational efficiency, resulting in a more effective digital experience.",
    mainImage: '/ontap-squared.jpg',
    mainImageAlt: 'onTap banner image',
    topBanner: '/ontap-squared.jpg',
    roleOnProject: 'Frontend Developer',
    problemOneImage: '/ontap/ontap-first-task.png',
    problemOneText: 'Implemented a custom filtering mechanism for a Vue Storefront application to enhance data management and presentation. This solution facilitates the handling of data received from the Advance endpoint API, ensuring that all relevant data is processed on the frontend.\n\nThe filter allows for dynamic adjustment of data visibility, enabling precise control over which information is displayed to users. This approach not only optimizes the user experience by presenting relevant content but also improves the efficiency of data handling and display within the application.',
    problemTwoImage: '/ontap/ontap-navigation.mp4',
    problemTwoText: "At the outset, Vue Storefront's default setup supported only a single layer of navigation. When onTap proposed a requirement for multi-level navigation to enhance their user interface, I undertook the challenge of customizing the platform.\n\nI achieved this by overriding core components and extending the navigation capabilities to accommodate multiple hierarchical levels. This modification allowed onTap to implement a more complex and user-friendly navigation structure, tailored to their specific needs.\n\nBy extending the default navigation functionality, I ensured that the application could handle intricate navigation schemes, thereby improving the overall user experience and meeting onTap's requirements for a more sophisticated and flexible navigation system."
  },
  {
    project: "onTap",
    slug: "ontap-test",
    websiteURL: 'https://www.ontap.co.za/',
    techStack: ['Vue.JS', 'C# backend', 'Vue Storefront'],
    favourited: false,
    shortDescription: "From 2020 to 2021, onTap partnered with our agency to elevate its digital presence. We modernized their platform with Vue Storefront and integrated it with Nologo's 'Advance' backend system in C#.\n\nOur aim was to boost user engagement and streamline backend operations to align with onTap's business goals.",
    longDescription: "From 2020 to 2021, onTap partnered with our agency to elevate its digital presence. We modernized their platform with Vue Storefront and integrated it with Nologo's 'Advance' backend system in C#.\n\nOur aim was to boost user engagement and streamline backend operations to align with onTap's business goals.",
    mainImage: '/ontap-squared.jpg',
    mainImageAlt: 'onTap banner image',
    topBanner: '/ontap-squared.jpg',
    roleOnProject: 'Frontend Developer',
    problemOneImage: '/ontap/ontap-first-task.png',
    problemOneText: 'Implemented a custom filtering mechanism for a Vue Storefront application to enhance data management and presentation. This solution facilitates the handling of data received from the Advance endpoint API, ensuring that all relevant data is processed on the frontend.\n\nThe filter allows for dynamic adjustment of data visibility, enabling precise control over which information is displayed to users. This approach not only optimizes the user experience by presenting relevant content but also improves the efficiency of data handling and display within the application.',
    problemTwoImage: '/ontap/ontap-navigation.mp4',
    problemTwoText: "At the outset, Vue Storefront's default setup supported only a single layer of navigation. When onTap proposed a requirement for multi-level navigation to enhance their user interface, I undertook the challenge of customizing the platform.\n\nI achieved this by overriding core components and extending the navigation capabilities to accommodate multiple hierarchical levels. This modification allowed onTap to implement a more complex and user-friendly navigation structure, tailored to their specific needs.\n\nBy extending the default navigation functionality, I ensured that the application could handle intricate navigation schemes, thereby improving the overall user experience and meeting onTap's requirements for a more sophisticated and flexible navigation system."
  }
]